version: '3'

networks:
  default:

services:

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - default

  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - 8812:8812
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - redis
      - kafka
      - postgres
    networks:
      - default

  supplier:
    build:
      context: supplier
      dockerfile: Dockerfile
    container_name: supplier
    ports:
      - 8811:8811
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      - kafka
    networks:
      - default

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - default

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    ports:
      - 8813:8081
    networks:
      - default

volumes:
  postgres:
  pgadmin: