version: '3'

services:

  #kafka:
    #image: wurstmeister/kafka
    #container_name: kafka-multibinder
    #ports:
      #- "9092:9092"
    #environment:
      #- KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      #- KAFKA_ADVERTISED_PORT=9092
      #- KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    #depends_on:
      #- zookeeper

  #zookeeper:
    #image: wurstmeister/zookeeper
    #ports:
      #- "2181:2181"
    #environment:
      #- KAFKA_ADVERTISED_HOST_NAME=zookeeper

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-multibinder
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default


  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - 8812:8812
    #environment:
    #  SPRING_DATASOURCE_URL: jdbc:postgresql://asset_registry_postgres:5432/asset_registry_db
    #  SPRING_RABBITMQ_HOST: rabbitmq0
    #networks:
    #  - core
    #  - default
    depends_on:
      - redis
    networks:
      - default

  supplier:
    build:
      context: supplier
      dockerfile: Dockerfile
    container_name: supplier
    ports:
      - 8811:8811
    #environment:
    #  SPRING_DATASOURCE_URL: jdbc:postgresql://asset_registry_postgres:5432/asset_registry_db
    #  SPRING_RABBITMQ_HOST: rabbitmq0
    #networks:
    #  - core
    #  - default
    depends_on:
      - rabbitmq
    networks:
      - default

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    networks:
      - default

